Revert "hal: Fix combo device issue with routing change"
This reverts commit 1be15993478ee171c1bd712a02506dfa767c0850.

hardware/qcom/audio-caf/msm8998/hal/audio_extn/utils.c:2522:55: error: unused parameter 'snd_device'
[-Werror,-Wunused-parameter]
void audio_extn_utils_release_snd_device(snd_device_t snd_device)
                                                      ^

Change-Id: If4ed8ddf44ab122cbb3c8b051240d7cb3aa148c7